### ISSUE TITLE
Change vis_* to take CHW images as input

### ISSUE THREAD

**Issue by yuyu2172** [pfnet/chainercv#123]
Currently, visualization functions such as `vis_bbox` take an image in HWC format and uint8 dtype.
This is inconsistent with the interface of transforms.

The  `vis_*` should be modified to take images which are

+ CHW
+ `dtype == np.float32`

This change will involve not only to `vis_*`, but also extensions supported in `chainercv/extensions`.

**Comment by Hakuyume** [comment]
#124 and #135 solved this issue.
