### ISSUE TITLE
Argument for dataset to determine split is vague

### ISSUE THREAD

**Issue by yuyu2172** [pfnet/chainercv#131]
Currently an option to determine train/val/test split of a dataset is determined by a keyword `mode`.
I think this is vague, and possibly be improved.

One option is to use a keyword `split`.

**Comment by yuyu2172** [comment]
@Hakuyume 

What do you think about this issue?

**Comment by Hakuyume** [comment]
@yuyu2172 I agree `mode` is not good. How about `subset`?

**Comment by yuyu2172** [comment]
Sure. I think both `split` and `subset are fine.

**Comment by Hakuyume** [comment]
I think `split` is also good. Both of them make sense.
