### ISSUE TITLE
Representation for batch of bounding boxes

### ISSUE THREAD

**Issue by yuyu2172** [pfnet/chainercv#163]
There are three possible representations for batch of bounding boxes.

1. An array of shape `(B, R, 4)`.
2. A coordinate array and a batch index array. They are shape `(R', 4)` and `(R',)` respectively. This representation is used for `chainer.functions.roi_pooling_2d`.
3. List of `(R, 4)` arrays

The convention on the conditions for selecting representations had not been discussed extensively yet, and I would like to discuss it here.

First of all, I would like to summarize examples found in the code.

+ For a function that takes list of images as input and returns bounding box (`List[img] -> BBox`), list of `(R, 4)` arrays is used. This is found in `predict` of detection links.
+ For a function that takes batch of image arrays as input and returns bounding box (`BCHW -> BBox`), batch of bounding box arrays (i.e. an array of shape `(B, R, 4)`) is used. This is found in `SSD.__call__`. 

Here are rules that I am thinking of.

+ When number of bounding boxes per image is fixed, use `(B, R, 4)`.
+ When number of bounding boxes per image is varying, use `(R', 4)` and `(R',)`.
+ When it is output of a function with list of images as input, return list of `(R, 4)`.

For the second case, I chose not to use list of `(R, 4)` because of efficiency reasons.
Since list of `(R, 4)` can easily be copied to `(R', 4)` and `(R',)` internally, the overhead it creates is little. However, this can create non-negligible overhead when this comes with other data type.

For example, I would like to consider a case when we want to write a function that takes batch of images and list of bounding boxes as input and returns a cropped image with same shape per bounding box (i.e. Inputs: `(B, C, H, W)` and list of `(R, 4)`, Output: Length B list of `(R, C, H', W')`). List of batched images is hard to efficiently work with when we want to do batch image operations like batched matrix multiplications. Thus, it is better to represent them as one chunk of array with index array used separately.

EDIT:
Variable length bounding boxes shows up in Region Proposal Network in Faster RCNN.
They output NMSed bounding boxes as RoI proposals, and these bounding boxes can in principle be variable length.

https://github.com/yuyu2172/chainercv/blob/faster-rcnn-test/chainercv/links/model/faster_rcnn/region_proposal_network.py#L117

https://github.com/yuyu2172/chainercv/blob/faster-rcnn-test/chainercv/links/model/faster_rcnn/utils/proposal_creator.py

**Comment by Hakuyume** [comment]
> When number of bounding boxes per image is varying, use (R', 4) and (R',).

Let me confirm. `(R', 4)` is the coordinates of bounding boxes and `(R')` is the indices of corresponding image in input batch. Is it right? 

I think this is a trade-off problem between simplicity of APIs and efficiency. 
If we use list of `(R', 4)` format for batched images, the APIs will be more simple because `(R', 4)`  and `(R',)` format is very different from other two. We can convert it to `(R', 4)`  and `(R',)` format internally if needed. As you pointed out, this conversion will cause an overhead. Actually, I don't know how large the overhead will be.  But I guess the overhead will not be so large and we can choose simplicity of APIs. 

> However, this can create non-negligible overhead when this comes with other data type.

**Comment by yuyu2172** [comment]
> Let me confirm. (R', 4) is the coordinates of bounding boxes and (R') is the indices of corresponding image in input batch. Is it right?

Yes. Thanks for confirming.

**Comment by yuyu2172** [comment]
As I pointed out in the initial post, the convention needs to be carried on when bbox comes with other data type.
This means that variable sized batch of images need to be represented by the same convention used for bbox.
Concatenating list of batched images may introduce non-negligible overheads.

**Comment by Hakuyume** [comment]
> Concatenating list of batched images may introduce non-negligible overheads.

Perhaps, I am misunderstanding. `Concatenating list of batched images` is `list of (B, C, H, W)` -> `(N, B, C, H, W)`?

**Comment by yuyu2172** [comment]
`Concatenating list of batched images` means `[(R_1, C, H, W) ... , (R_B, C, H, W)]` -> `(R_1 + ... + R_B, C, H, W)`.

**Comment by yuyu2172** [comment]
In terms of simplicity, I am not sure if list of bbox is better.
Since you need to convert batch array representation back into list representation whenever exposing values publicly, extra conversion code becomes necessary making internal code less obvious.

For example, I tried this convention in a building block of Faster RCNN, and it required me some extra conversion codes that do not look nice to me.
In the code, a function takes `(B, C, H, W)` and list of bboxes as inputs and returns list of `(R, C)`.

https://github.com/yuyu2172/chainercv/blob/4e25beb116336c4c7c1462b752f38937cae1a2db/chainercv/links/model/faster_rcnn/faster_rcnn_vgg.py#L94

**Comment by yuyu2172** [comment]
@Hakuyume 

What do you think?

**Comment by Hakuyume** [comment]
> Since you need to convert batch array representation back into list representation whenever exposing values publicly, extra conversion code becomes necessary making internal code less obvious.

What I was talking about is simplicity of APIs. I thought less representations are better. As you pointed out, internal conversion code makes the code a little complicated but I think it is acceptable.

**Comment by yuyu2172** [comment]
Here are rules we will be using.

+ `bb` is a `(R,)`
+ `bbox` is a `(R, 4)`
+ `bboxes` is a `(B, R, 4)` or list of `(R_i, 4)  i=1, ..., B`.
+ `rois` is a `(R', 4)` which consists of bounding boxes for multiple images. Assuming that there are B images each containing `R_i` bounding boxes, `R' = \sum R_i`. `rois` comes together with a `(R',)` array called `batch_indices`, which contains batch indices of images to which bounding boxes correspond to.
