### ISSUE TITLE
Format of keypoint

### ISSUE THREAD

**Issue by Hakuyume** [pfnet/chainercv#52]
This issue is similar to #46.
Currently, we use a ndarray whose shape is (3,) for the format of keypoint.
https://github.com/pfnet/chainercv/blob/master/chainercv/transforms/keypoint/resize_keypoint.py#L4

However, `vaild` is always bool while `x` and `y` may be float.
It is better to split into two arrays, `(x, y)` and `valid` whose shapes are `(K, 2)` and `(K,)`.

**Comment by yuyu2172** [comment]
Thanks for pointing that out.
I agree that `(K, 2)` and `(K,)` are better.

**Comment by yuyu2172** [comment]
This issue is solved.
