### ISSUE TITLE
Inconsistency in arguments of transforms/image

### ISSUE THREAD

**Issue by yuyu2172** [pfnet/chainercv#83]
Many image transform functions take some kind of argument to decide whether to return intermediate variables or not (e.g. `return_params` in `random_expand`).
These variables are necessary when handling multiple data types. For example, bounding boxes need to be transformed according to the transformation done to images.

The issue is that parameters used to control the behavior is inconsistent among transforms.
I think that the current API is confusing for users.

Examples of (function, parameter) pairs.
+ `random_expand` takes `return_params`
+ `random_crop` takes `return_slices`.
+  `random_flip` takes `return_flips`.

**Comment by Hakuyume** [comment]
How about always returning a dictionary which contains drawn parameters.
Here is an example.
```
dst_img, params = random_expand(src_img)
# params: {'ratio': ***, 'x_offset': ***, 'y_offset': ***}

dst_img, params = random_crop(src_img, (***, ***))
# params: {'x_slice': ***, 'y_slice': ***}
```

If users do not need params, they can write
```
dst_img, _ = random_*(src_img, ...)
```

**Comment by yuyu2172** [comment]
I think what you proposed is simple and nice.
However, I have a concern that it is not clear as to which transforms return params.

For example, `center_crop` returns params too. Also, I think `ten_crop` should return it too (although it does not in status quo). These parameters become helpful when users want to use `center_crop` together with other data types (e.g. bounding boxes).

**Comment by yuyu2172** [comment]
There are three options

+ making params optional for `random_*` and transforms such as `center_crop`
+ params is not optional for `random_*`, but optional for `center_crop`
+ params is not optional for all transforms.

**Comment by Hakuyume** [comment]
I think the third option is the best. In this case, all functions without computed params, such as `flip` and `pad`, should return empty dictionaries.

**Comment by yuyu2172** [comment]
Thanks for your opinion.
I think that there is still a room left on how to decide parameter convention for transforms that act on non-
image data types.
If we make those transforms to return params as well, I think that it looks redundant and in most cases unnecessary.
Instead, if we do not make those transforms to return params, it would defeat the purpose because consistency will be lost.

Considering those points, I would rather make all transforms to have optional parameter `return_params` if necessary. 

I compared both options in some example codes I had.

#### Semantic Segmentation Example (one in examples)
```python
    # prepare datasets
    def transform(in_data):
        img, label = in_data
        vgg_subtract_bgr = np.array(
            [103.939, 116.779, 123.68], np.float32)[:, None, None]
        img -= vgg_subtract_bgr
        img, _ = transforms.pad(img, max_size=(512, 512), bg_value=0)
        label, _ = transforms.pad(label, max_size=(512, 512), bg_value=-1)
        return img, label
```


#### Detection example (with no return_param)

```python

def transform(in_data):
    img, bbox = in_data
    img -= np.array([103.939, 116.779, 123.68])[:, None, None]

    # Resize bounding box to a shape
    # with the smaller edge at least at length 600
    input_shape = img.shape[1:]
    img, _ = transforms.scale(img, 600)
    output_shape = img.shape[1:]
    bbox, _ = transforms.resize_bbox(bbox, input_shape, output_shape)

    # horizontally flip
    img, params = transforms.random_flip(img, x_random=True)
    bbox, _ = transforms.flip_bbox(bbox, output_shape, params['x_flip'])
    return img, bbox
```


### Detection example (with return_param)
```python

def transform(in_data):
    img, bbox = in_data
    img -= np.array([103.939, 116.779, 123.68])[:, None, None]

    # Resize bounding box to a shape
    # with the smaller edge at least at length 600
    input_shape = img.shape[1:]
    img = transforms.scale(img, 600)
    output_shape = img.shape[1:]
    bbox = transforms.resize_bbox(bbox, input_shape, output_shape)

    # horizontally flip
    img, param = transforms.random_flip(img, x_random=True, return_param=True)
    bbox= transforms.flip_bbox(bbox, output_shape, param['x_flip'])
    return img, bbox
```
